name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - run: ls -lasR

      - name: Install and Build
        uses: actions/setup-node@v1
      - run: chmod -R +x ./scripts/
      - run: ./scripts/export.sh
        env: 
          CI: true
      - run: touch ./blog/out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          SSH-KEY: ${{ secrets.SSH_KEY }}
          BRANCH: gh-pages
          FOLDER: ./blog/out
          CLEAN: true
